import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';

@Component({ selector: 'app-application-detail', standalone: true, imports: [CommonModule, FormsModule], template: `
<div *ngIf="app">
  <div class="page-head"><div><div class="eyebrow">{{app.applicationNumber}}</div><h1>{{app.applicant?.firstName}} {{app.applicant?.lastName}}</h1><p>Requested {{app.requestedLoanAmount|currency:'USD':'symbol':'1.0-0'}} · {{pretty(app.property?.propertyType)}} · {{app.tenant?.name}}</p></div><span class="status large">{{pretty(app.status)}}</span></div>
  <div class="summary-grid"><div class="summary-card"><span>Credit score</span><strong>{{credit?.creditScore||'—'}}</strong><small>{{credit?.provider||'No provider result'}}</small></div><div class="summary-card"><span>DTI</span><strong>{{financial?.debtToIncomeRatio ? (financial.debtToIncomeRatio|number:'1.1-1')+'%' : '—'}}</strong><small>Debt-to-income</small></div><div class="summary-card"><span>LTV</span><strong>{{financial?.loanToValueRatio ? (financial.loanToValueRatio|number:'1.1-1')+'%' : '—'}}</strong><small>Loan-to-value</small></div><div class="summary-card"><span>Recommendation</span><strong class="small-strong">{{pretty(run?.recommendation)||'Not run'}}</strong><small>Engine {{run?.engineVersion||'—'}}</small></div></div>
  <div class="card"><div class="card-head"><div><h3>Provider and underwriting actions</h3><p>All provider results are synthetic and persisted for this tenant.</p></div><div class="actions"><button class="btn" (click)="runCredit()">Run mock credit</button><button class="btn" (click)="runAus()">Run Demo AUS</button><button class="btn primary" (click)="runUnderwriting()">Run underwriting</button></div></div><div *ngIf="message" class="demo-banner">{{message}}</div></div>
  <div class="split"><div class="card"><div class="card-head"><div><h3>Underwriting findings</h3><p>Deterministic, explainable rule evaluations.</p></div></div><div *ngIf="!run" class="empty">Run underwriting to evaluate the current tenant policy.</div><div *ngFor="let e of run?.evaluations" class="finding"><div><b>{{pretty(e.ruleCode)}}</b><p>{{e.explanation}}</p></div><span class="outcome" [class.review]="e.outcome==='REVIEW'" [class.decline]="e.outcome==='DECLINE'">{{e.outcome}}</span></div></div><div class="card"><div class="card-head"><div><h3>Demo AUS</h3><p>Submission history</p></div></div><div *ngFor="let a of app.ausSubmissions" class="finding"><div><b>{{a.provider}}</b><p>{{a.createdAt|date:'medium'}}</p></div><span class="status">{{a.recommendation}}</span></div><div *ngIf="!app.ausSubmissions?.length" class="empty">No AUS submissions yet.</div></div></div>
  <div class="card"><div class="card-head"><div><h3>Documents</h3><p>Private tenant-aware storage. PDFs use text extraction with local OCR fallback.</p></div></div><div class="upload-row"><label>Document type<select [(ngModel)]="documentType"><option>PAYSLIP</option><option>BANK_STATEMENT</option><option>CREDIT_REPORT</option><option>IDENTITY</option><option>TAX_RETURN</option></select></label><label>File<input type="file" accept="application/pdf,image/jpeg,image/png" (change)="selectFile($event)"></label><button class="btn primary" (click)="upload()" [disabled]="!selectedFile||uploading">{{uploading?'Uploading…':'Upload document'}}</button></div><div *ngFor="let d of app.documents" class="doc-row"><div><b>{{pretty(d.type)}}</b><span>{{d.fileName}} <em *ngIf="d.extractedJson">· extracted</em><em *ngIf="d.extractedJson?.fields?.creditScore"> · score {{d.extractedJson.fields.creditScore}}</em></span></div><span class="status">{{pretty(d.status)}}</span><button class="btn" (click)="download(d)">Download</button></div><div *ngIf="!app.documents?.length" class="empty">No documents uploaded.</div></div>
  <div class="card"><div class="card-head"><div><h3>Conditions</h3><p>Condition status history is retained for audit.</p></div><button class="btn" (click)="addCondition()">Add source-of-funds condition</button></div><div *ngFor="let c of app.conditions" class="finding"><div><b>{{c.title}}</b><p>{{c.description}}</p></div><div><span class="status">{{pretty(c.status)}}</span><button *ngIf="c.status!=='SATISFIED'" class="btn" (click)="satisfy(c)">Mark satisfied</button></div></div><div *ngIf="!app.conditions?.length" class="empty">No conditions.</div></div>
  <div class="split"><div class="card"><div class="card-head"><div><h3>Financial snapshot</h3><p>Current declared values.</p></div></div><dl class="detail-list"><div><dt>Gross monthly income</dt><dd>{{app.employment?.grossMonthlyIncome|currency:'USD'}}</dd></div><div><dt>Property value</dt><dd>{{app.property?.estimatedValue|currency:'USD'}}</dd></div><div><dt>Assets</dt><dd>{{totalAssets|currency:'USD'}}</dd></div><div><dt>Monthly debt</dt><dd>{{monthlyDebt|currency:'USD'}}</dd></div></dl></div><div class="card"><div class="card-head"><div><h3>Final decision</h3><p>Human decision is separate from the system recommendation.</p></div></div><label>Reason<textarea [(ngModel)]="reason" rows="3"></textarea></label><div class="actions"><button class="btn success-btn" (click)="decide('APPROVED')">Approve</button><button class="btn" (click)="decide('REQUEST_DOCUMENTS')">Request documents</button><button class="btn danger-btn" (click)="decide('DECLINED')">Decline</button></div></div></div>
  <div class="card"><div class="card-head"><div><h3>Audit trail</h3><p>Append-only workflow events for traceability.</p></div></div><div class="timeline"><div *ngFor="let e of app.auditEvents"><span></span><div><b>{{pretty(e.action)}}</b><small>{{e.createdAt|date:'medium'}}</small></div></div></div></div>
</div>` })
export class ApplicationDetailComponent implements OnInit {
  app:any; reason='Reviewed applicant and supporting portfolio evidence.'; message=''; selectedFile?:File; documentType='PAYSLIP'; uploading=false;
  constructor(private route:ActivatedRoute, private api:ApiService){}
  ngOnInit(){this.load()}
  load(){this.api.application(this.route.snapshot.paramMap.get('id')!).subscribe(a=>this.app=a)}
  get credit(){return this.app?.creditReports?.[0]}
  get financial(){return this.app?.financialAssessments?.[0]}
  get run(){return this.app?.underwritingRuns?.[0]}
  get totalAssets(){return (this.app?.assets||[]).reduce((s:number,a:any)=>s+Number(a.currentValue),0)}
  get monthlyDebt(){return (this.app?.liabilities||[]).reduce((s:number,a:any)=>s+Number(a.monthlyPayment),0)}
  pretty(s:string){return s?.replaceAll('_',' ')||''}
  selectFile(event:Event){this.selectedFile=(event.target as HTMLInputElement).files?.[0]}
  upload(){if(!this.selectedFile)return;this.uploading=true;this.message='';this.api.uploadDocument(this.app.id,this.selectedFile,this.documentType).subscribe({next:()=>{this.message='Document queued for local processing.';this.uploading=false;this.load()},error:e=>{this.message=e?.error?.message||'Upload failed';this.uploading=false}})}
  download(doc:any){this.api.downloadDocument(this.app.id,doc.id).subscribe(response=>{const url=URL.createObjectURL(response.body!);const anchor=document.createElement('a');anchor.href=url;anchor.download=doc.fileName;anchor.click();URL.revokeObjectURL(url)})}
  runCredit(){this.api.creditRun(this.app.id).subscribe({next:()=>{this.message='Mock credit provider completed.';this.load()},error:e=>this.message=e?.error?.message||'Credit check failed'})}
  runAus(){this.api.ausRun(this.app.id).subscribe({next:()=>{this.message='Demo AUS submission persisted.';this.load()},error:e=>this.message=e?.error?.message||'AUS submission failed'})}
  runUnderwriting(){this.api.underwrite(this.app.id).subscribe({next:()=>{this.message='Underwriting run persisted.';this.load()},error:e=>this.message=e?.error?.message||'Underwriting failed'})}
  addCondition(){this.api.createCondition(this.app.id,{code:'SOURCE_LARGE_DEPOSIT',title:'Source large deposit',description:'Document and explain the synthetic large deposit.'}).subscribe({next:()=>{this.message='Condition created.';this.load()},error:e=>this.message=e?.error?.message||'Condition creation failed'})}
  satisfy(c:any){this.api.transitionCondition(this.app.id,c.id,'SATISFIED').subscribe({next:()=>{this.message='Condition marked satisfied.';this.load()},error:e=>this.message=e?.error?.message||'Condition update failed'})}
  decide(d:string){this.api.decide(this.app.id,d,this.reason).subscribe({next:r=>{this.message=`Decision recorded: ${r.finalDecision}`;this.load()},error:e=>this.message=e?.error?.message||'Decision failed'})}
}
