import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { ApplicationSummary } from '../models';
@Component({selector:'app-applications',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<div class="page-head"><div><div class="eyebrow">Pipeline</div><h1>Mortgage applications</h1><p>Review applicant, financial and underwriting state in one place.</p></div><button class="btn primary" (click)="showCreate=!showCreate">+ New application</button></div>
<div class="card create-panel" *ngIf="showCreate"><div class="card-head"><div><h3>Start mortgage application</h3><p>Credit is requested from the mock provider after the application is submitted.</p></div></div><div class="form-grid"><label>First name<input [(ngModel)]="form.firstName"></label><label>Last name<input [(ngModel)]="form.lastName"></label><label>Email<input type="email" [(ngModel)]="form.email"></label><label>Requested loan<input type="number" min="1" [(ngModel)]="form.requestedLoanAmount"></label><label>Property value<input type="number" min="1" [(ngModel)]="form.propertyValue"></label><label>Gross monthly income<input type="number" min="1" [(ngModel)]="form.grossMonthlyIncome"></label><label>Monthly debt<input type="number" min="0" [(ngModel)]="form.monthlyDebt"></label></div><div class="actions"><button class="btn" (click)="showCreate=false" [disabled]="creating">Cancel</button><button class="btn primary" (click)="create()" [disabled]="creating">{{creating ? 'Creating…' : 'Start application'}}</button></div><div *ngIf="message" class="demo-banner">{{message}}</div></div>
<div class="card"><div class="table-wrap"><table><thead><tr><th>Application</th><th>Applicant</th><th>Loan</th><th>Credit</th><th>DTI</th><th>Status</th><th></th></tr></thead><tbody><tr *ngFor="let a of apps"><td><b>{{a.applicationNumber}}</b><span class="table-sub">Updated {{a.updatedAt|date:'mediumDate'}}</span></td><td>{{a.applicant?.firstName}} {{a.applicant?.lastName}}<span class="table-sub">{{a.applicant?.email}}</span></td><td>{{a.requestedLoanAmount|currency:'USD':'symbol':'1.0-0'}}</td><td>{{a.creditReports?.[0]?.creditScore||'—'}}</td><td>{{a.financialAssessments?.[0]?.debtToIncomeRatio ? (a.financialAssessments?.[0]?.debtToIncomeRatio|number:'1.1-1')+'%' : '—'}}</td><td><span class="status">{{pretty(a.status)}}</span></td><td><a [routerLink]="['/applications',a.id]">Open →</a></td></tr></tbody></table></div></div>`})
export class ApplicationsComponent implements OnInit{apps:ApplicationSummary[]=[];showCreate=false;creating=false;message='';form:any={firstName:'Alex',lastName:'Morgan',email:'alex.morgan@example.test',requestedLoanAmount:300000,propertyValue:400000,grossMonthlyIncome:9000,monthlyDebt:2800,loanPurpose:'PURCHASE',occupancyType:'PRIMARY_RESIDENCE'};constructor(private api:ApiService){}ngOnInit(){this.load()}load(){this.api.applications().subscribe({next:a=>this.apps=a,error:e=>this.message=e?.error?.message||'Could not load applications.'})}create(){this.message='';if(!this.form.firstName||!this.form.lastName||!this.form.email||!this.form.requestedLoanAmount||!this.form.propertyValue||!this.form.grossMonthlyIncome||this.form.monthlyDebt===null||this.form.monthlyDebt===undefined){this.message='Please complete all application fields.';return}this.creating=true;this.api.createApplication(this.form).subscribe({next:app=>{this.creating=false;this.showCreate=false;this.message=`Application ${app.applicationNumber} created.`;this.load()},error:e=>{this.creating=false;this.message=e?.error?.message||'Application creation failed.'}})}pretty(s:string){return s?.replaceAll('_',' ')}}
