import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../core/api.service';

@Component({selector:'app-consumer-application',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-head"><div><div class="eyebrow">Application details</div><h1>My application</h1><p>Review the information saved for your synthetic mortgage application.</p></div><span *ngIf="app" class="status large">{{pretty(app.status)}}</span></div>
<div *ngIf="app" class="split"><div class="card"><div class="card-head"><div><h3>Borrower information</h3><p>Contact details for this demonstration application.</p></div></div><div class="form-grid"><label>First name<input [(ngModel)]="app.applicant.firstName"></label><label>Last name<input [(ngModel)]="app.applicant.lastName"></label><label>Email<input [(ngModel)]="app.applicant.email"></label></div><div class="actions"><button class="btn primary" (click)="save()">Save details</button></div></div><div class="card"><div class="card-head"><div><h3>Loan & property</h3><p>{{app.loan?.productName}}</p></div></div><dl class="detail-list"><div><dt>Requested loan</dt><dd>{{app.requestedLoanAmount|currency:'USD'}}</dd></div><div><dt>Property value</dt><dd>{{app.property?.estimatedValue|currency:'USD'}}</dd></div><div><dt>Occupancy</dt><dd>{{pretty(app.property?.occupancyType)}}</dd></div></dl></div></div>
<div *ngIf="app" class="card"><div class="card-head"><div><h3>Documents</h3><p>Upload a requested document and download a copy of anything already submitted.</p></div></div><div class="upload-row"><label>Document type<select [(ngModel)]="documentType"><option>PAYSLIP</option><option>BANK_STATEMENT</option><option>CREDIT_REPORT</option><option>IDENTITY</option><option>TAX_RETURN</option></select></label><label>File<input type="file" accept="application/pdf,image/jpeg,image/png" (change)="selectFile($event)"></label><button class="btn primary" (click)="upload()" [disabled]="!selectedFile||uploading">{{uploading?'Uploading…':'Upload document'}}</button></div><div *ngFor="let d of app.documents" class="doc-row"><div><b>{{pretty(d.type)}}</b><span>{{d.fileName}}</span></div><span class="status">{{pretty(d.status)}}</span><button class="btn" (click)="download(d)">Download</button></div></div><div *ngIf="message" class="demo-banner">{{message}}</div>`})
export class ConsumerApplicationComponent implements OnInit { app:any; message=''; selectedFile?:File; documentType='PAYSLIP'; uploading=false; constructor(private api:ApiService){} ngOnInit(){this.load()} load(){this.api.applications().subscribe(a=>{if(a[0])this.api.application(a[0].id).subscribe(x=>this.app=x)})} pretty(s:string){return s?.replaceAll('_',' ')||''} selectFile(e:Event){this.selectedFile=(e.target as HTMLInputElement).files?.[0]} save(){this.message='Details saved for this synthetic application.'} upload(){if(!this.selectedFile)return;this.uploading=true;this.api.uploadDocument(this.app.id,this.selectedFile,this.documentType).subscribe({next:()=>{this.message='Document uploaded and queued for processing.';this.uploading=false;this.load()},error:e=>{this.message=e?.error?.message||'Upload failed';this.uploading=false}})} download(d:any){this.api.downloadDocument(this.app.id,d.id).subscribe(r=>{const url=URL.createObjectURL(r.body!);const a=document.createElement('a');a.href=url;a.download=d.fileName;a.click();URL.revokeObjectURL(url)})} }
