import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { Dashboard } from '../models';
@Component({selector:'app-dashboard',standalone:true,imports:[CommonModule,RouterLink],template:`
<div class="page-head"><div><div class="eyebrow">Portfolio</div><h1>Good afternoon</h1><p>Monitor mortgage applications, underwriting readiness and risk decisions.</p></div><a class="btn primary" routerLink="/applications">Open applications</a></div>
<div class="metrics" *ngIf="data"><div class="metric"><span>Total applications</span><strong>{{data.metrics.total}}</strong><small>Across current portfolio</small></div><div class="metric"><span>Ready</span><strong>{{data.metrics.ready}}</strong><small>Ready for underwriting</small></div><div class="metric warning"><span>Manual review</span><strong>{{data.metrics.manualReview}}</strong><small>Needs human judgement</small></div><div class="metric success"><span>Approved</span><strong>{{data.metrics.approved}}</strong><small>Final decisions</small></div><div class="metric danger"><span>Declined</span><strong>{{data.metrics.declined}}</strong><small>Final decisions</small></div></div>
<div class="card"><div class="card-head"><div><h3>Recent applications</h3><p>Latest mortgage cases and current workflow status.</p></div></div><div class="table-wrap"><table><thead><tr><th>Application</th><th>Applicant</th><th>Loan</th><th>Underwriter</th><th>Status</th><th></th></tr></thead><tbody><tr *ngFor="let a of data?.recent"><td><b>{{a.applicationNumber}}</b></td><td>{{a.applicant?.firstName}} {{a.applicant?.lastName}}</td><td>{{a.requestedLoanAmount | currency:'USD':'symbol':'1.0-0'}}</td><td>{{a.underwriter?.displayName||'Unassigned'}}</td><td><span class="status">{{pretty(a.status)}}</span></td><td><a [routerLink]="['/applications',a.id]">Review →</a></td></tr></tbody></table></div></div>`})
export class DashboardComponent implements OnInit{data?:Dashboard;constructor(private api:ApiService){}ngOnInit(){this.api.dashboard().subscribe(d=>this.data=d)}pretty(s:string){return s?.replaceAll('_',' ')}}
